'use strict';

/**
 * Tạo database/hcm_flood_neon.sql từ hcm_flood.sql:
 * - Bỏ data: access_logs, flood_logs, energy_logs, alerts
 * - Giữ users (reset is_online = false), sensors, crowd_reports, ...
 * - Bỏ \\restrict / \\unrestrict (pg_dump 18)
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'database', 'hcm_flood.sql');
const OUT = path.join(__dirname, '..', 'database', 'hcm_flood_neon.sql');

/** Bảng chỉ giữ COPY rỗng (schema + FK vẫn từ dump). */
const STRIP_DATA_TABLES = new Set(['access_logs', 'flood_logs', 'energy_logs', 'alerts']);

const STRIP_SEQ_PREFIXES = ['access_logs_id_seq', 'flood_logs_id_seq', 'energy_logs_id_seq', 'alerts_id_seq'];

function normalizeUserRow(line) {
    if (!line.trim() || line === '\\.') return line;
    const parts = line.split('\t');
    if (parts.length >= 12) parts[11] = 'f';
    return parts.join('\t');
}

function main() {
    const lines = fs.readFileSync(SRC, 'utf8').split(/\r?\n/);
    const out = [
        '-- Generated by scripts/buildNeonImportDump.js — import lên Neon',
        '-- Reset schema public rồi nạp DDL + data đã lọc',
        'DROP SCHEMA IF EXISTS public CASCADE;',
        'CREATE SCHEMA public;',
        'GRANT ALL ON SCHEMA public TO PUBLIC;',
        '',
    ];

    let inCopy = false;
    let stripData = false;
    let copyTable = null;

    for (const line of lines) {
        if (line.startsWith('\\restrict') || line.startsWith('\\unrestrict')) continue;
        if (/OWNER TO postgres/.test(line)) continue;

        const copyMatch = line.match(/^COPY public\.(\w+)\s/);
        if (copyMatch) {
            inCopy = true;
            copyTable = copyMatch[1];
            stripData = STRIP_DATA_TABLES.has(copyTable);
            out.push(line);
            continue;
        }

        if (inCopy && line === '\\.') {
            inCopy = false;
            stripData = false;
            copyTable = null;
            out.push(line);
            continue;
        }

        if (inCopy) {
            if (stripData) continue;
            if (copyTable === 'users') {
                out.push(normalizeUserRow(line));
                continue;
            }
            out.push(line);
            continue;
        }

        const setvalMatch = line.match(
            /^SELECT pg_catalog\.setval\('public\.([^']+)'/
        );
        if (setvalMatch && STRIP_SEQ_PREFIXES.includes(setvalMatch[1])) {
            out.push(`SELECT pg_catalog.setval('public.${setvalMatch[1]}', 1, false);`);
            continue;
        }

        out.push(line);
    }

    fs.writeFileSync(OUT, out.join('\n'), 'utf8');
    const mb = (fs.statSync(OUT).size / 1024 / 1024).toFixed(2);
    console.log(`✅ Wrote ${OUT} (${mb} MB)`);
    console.log('   Stripped data:', [...STRIP_DATA_TABLES].join(', '));
}

main();
